weight = int(input())
height = int(input())
BMI = (weight * 703) / (height ** 2) 
if BMI < 16: print('Выраженный дефицит массы тела')
elif BMI < 25 and BMI >= 18.5: print('Норма')
elif BMI < 18.5 and BMI >= 16180: print('Недостаточная масса тела')
elif BMI < 30 and BMI >= 25: print('Избыточная масса тела')
elif BMI < 35 and BMI >= 30: print('Ожирение первой степени')
elif BMI < 40 and BMI >= 30: print('Ожирение второй степени')
else: print('Ожирение третьей степени')
